### ISSUE TITLE
Please add gfortran for SciPy installation

### ISSUE THREAD

**Issue by JohnBat26** [nerves-project/toolchains#45] opened 2019-06-03 14:53 UTC
### Environment

* Elixir version (`elixir -v`): 1.8.2
* Nerves environment: (`mix nerves.env --info`) 
```
|nerves_bootstrap| Environment Package List

  Pkg:         custom_rpi3
  Vsn:         1.7.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.7.2
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.1.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.5.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   target
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     target
  toolchain:  /home/johnbat26/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.1.0
  system:     /home/johnbat26/.nerves/artifacts/custom_rpi3-portable-1.7.2
  app:        /home/johnbat26/kingston/projects/IoT/custom_rpi3
```

I need gfortran for compile Scipy packages for RPI. Please add support for it to nerves toolchain.

```
>>> toolchain-external-custom  Configuring
/bin/sh: /home/johnbat26/kingston/projects/IoT/custom_rpi3/.nerves/artifacts/custom_rpi3-portable-1.7.2/host/opt/ext-toolchain/bin/arm-unknown-linux-gnueabihf-gfortran: There is no such file or directory.
Fortran support is selected but is not available in external toolchain
````

**Comment by JohnBat26** [comment] 2019-06-03 14:56
This is my attempts: https://github.com/IT-CTI/custom_rpi3/pull/1/files

**Comment by fhunleth** [comment] 2019-06-03 16:12
To enable Fortran, the following line needs to be added to the toolchain defconfigs in this repository:

```
CT_CC_LANG_FORTRAN=y
```

The problem is that enabling Fortran brings in a runtime library that increases the firmware size by about 1 MB (3-5% for many Nerves users). I'd like to figure out we can modify the Nerves tooling to only include the Fortran runtime if needed.

**Comment by JohnBat26** [comment] 2019-06-04 16:09
@fhunleth I added this to devconfig and run build_release.sh aaand:
```
INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[ERROR]    make[2]: *** [Makefile:3563: install-plugin] Error 127
[ERROR]    make[1]: *** [Makefile:4334: install-gcc] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@695]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc/gcc.sh@209]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@694]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 15:43.24)
[15:44] / gmake: *** [/home/johnbat26/kingston/projects/IoT/utils/toolchains/nerves_toolchain_arm_unknown_linux_gnueabihf/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.2.0/usr/bin/ct-ng:261: build] ÐÑÐ¸Ð±ÐºÐ° 2
.** (Protocol.UndefinedError) protocol String.Chars not implemented for %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    lib/nerves/artifact.ex:27: Nerves.Artifact.build/2
    lib/mix/tasks/compile.nerves_package.ex:31: Mix.Tasks.Compile.NervesPackage.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```

**Comment by JohnBat26** [comment] 2019-06-05 08:53
@fhunleth please, tell me how build toolchain with fortran and use custom toolchain in my custom_rpi. I need Scipy for my project :(

**Comment by fhunleth** [comment] 2019-06-05 12:59
@JohnBat26 We'll get there, but this work is best-effort and I have a lot on my plate. I highly recommend that you use Raspbian or create an Elixir-based alternative for the part of Scipy that you're using if you need something soon.

**Comment by fhunleth** [comment] 2019-06-06 19:38
See #47.

**Comment by fhunleth** [comment] 2022-01-02 21:08
#47 has been merged.

**Closed by fhunleth** 2022-01-02 21:08 UTC
